### ISSUE TITLE
nil for servers: NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by thewatts** [mperham/dalli#508]
I'm needing to adjust the max bytes size for Dalli.

I used the [example in the README for running on Heroku](https://github.com/mperham/dalli#usage-with-rails-3x-and-4x), specifically:

> If your servers are specified in ENV["MEMCACHE_SERVERS"] (e.g. on Heroku when using a third-party hosted addon), simply provide nil for the servers... 

Ex:

```ruby
# production.rb
config.cache_store = :dalli_store, nil, { value_max_bytes: 5242880 }
```

However, I receive this error: 

```
NoMethodError: undefined method `split' for nil:NilClass
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/server.rb:35:in `initialize'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/client.rb:309:in `new'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/client.rb:309:in `block in ring'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/client.rb:301:in `map'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/client.rb:301:in `ring'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/client.rb:142:in `flush'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/active_support/cache/dalli_store.rb:252:in `block (2 levels) in clear'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/dalli/client.rb:238:in `with'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/active_support/cache/dalli_store.rb:79:in `with'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/active_support/cache/dalli_store.rb:252:in `block in clear'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/active_support/cache/dalli_store.rb:348:in `block in instrument'
	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.8/lib/active_support/notifications.rb:161:in `instrument'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/active_support/cache/dalli_store.rb:348:in `instrument'
	from /app/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.0/lib/active_support/cache/dalli_store.rb:251:in `clear'
	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.8/lib/active_support/cache/strategy/local_cache.rb:99:in `clear'
	from (irb):1
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.8/lib/rails/commands/console.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.8/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.8/lib/rails/commands.rb:62:in `<top (required)>'
	from /app/bin/rails:4:in `require'
```

Any help would be greatly appreciated! Thanks!

**Comment by petergoldstein** [comment]
Closing, as the underlying cause was not library related.
