### ISSUE TITLE
Unexpected exception in Dalli: NameError: uninitialized constant LogoUploader

### ISSUE THREAD

**Issue by iamtarun** [mperham/dalli#513]
Hi,
 I am getting following issue on local and heroku also.
After clear cache i does not getting this.

Unexpected exception in Dalli: NameError: uninitialized constant LogoUploader::Uploader73381140
This is a bug in Dalli, please enter an issue in Github if it does not already exist.

Please suggest why this happend.

**Comment by petergoldstein** [comment]
@iamtarun I suspect you are deserializing an object that is either not serializable, or which refers to a class that has not yet been loaded at the time of deserialization.  Can you provide some details around LogoUploader and Uploader?  Where/how are they defined and are they required on Sidekiq worker startup?

**Comment by iamtarun** [comment]
This is LogoUploader code.............

class LogoUploader < CarrierWave::Uploader::Base

  include ::CarrierWave::Backgrounder::Delay
  include CarrierWave::RMagick
  
  
  # Recommended for use with fog
  include CarrierWave::MimeTypes
  process :set_content_type
  storage :fog
  #storage :file

  after :store, :kraken

  version :logo do
    process :resize_to_fit => [10000,75]
  end
  
  version :comm_logo do
    process :resize_to_fit => [10000,70]
  end

  version :small_logo do
    process :resize_to_fit => [10000,60]
  end

  def kraken(file)

    originalfile = "http://s3.amazonaws.com/" + ENV["FOG_DIRECTORY"] + "/" + store_dir + "/" + version_name.to_s + "_" + filename
    #Final path should be https://s3.amazonaws.com/whenwemarry-uploads/photos/6/kraken.jpg
    storepath = store_dir + "/" + version_name.to_s + "_" + filename


    kraken = Kraken::API.new(
        :api_key => ENV['KRAKEN_API'],
        :api_secret => ENV['KRAKEN_SECRET']
    )

    params = {}

    Rails.logger.info('Kraken About to Process: ' + originalfile);

    case version_name.to_s


      when "logo"
        params = {
                'lossy' => true,
                'resize' => {
                  'width' => 10000,
                  'height' => 75,
                  'strategy' => "auto",
                },
                's3_store' => {
                              'key' => ENV['AWS_ACCESS_KEY_ID'],
                              'secret' => ENV["AWS_SECRET_ACCESS_KEY"],
                              'bucket' => ENV["FOG_DIRECTORY"],
                              'acl' => 'public_read',
                              'path' => storepath
                              },
                  }

      when "small_logo"
        params = {
                'lossy' => true,
                'resize' => {
                  'width' => 10000,
                  'height' => 60,
                  'strategy' => "auto",
                },
                's3_store' => {
                              'key' => ENV['AWS_ACCESS_KEY_ID'],
                              'secret' => ENV["AWS_SECRET_ACCESS_KEY"],
                              'bucket' => ENV["FOG_DIRECTORY"],
                              'acl' => 'public_read',
                              'path' => storepath
                              },
                  }

      when "comm_logo"
        params = {
                'lossy' => true,
                'resize' => {
                  'width' => 10000,
                  'height' => 70,
                  'strategy' => "auto",
                },
                's3_store' => {
                              'key' => ENV['AWS_ACCESS_KEY_ID'],
                              'secret' => ENV["AWS_SECRET_ACCESS_KEY"],
                              'bucket' => ENV["FOG_DIRECTORY"],
                              'acl' => 'public_read',
                              'path' => storepath
                              },
                  }
    
    end


    #Store the file online

      if !version_name.blank?

        Rails.logger.info('UPLOADING TO: ' + store_path);


        data = kraken.url(originalfile,params)

        if data.success
            Rails.logger.info('KRAKEN: Success! Optimized image URL: ' + data.kraked_url)
        else
            puts 
            Rails.logger.info('KRAKEN: Fail. Error message: ' + data.message)
        end

      end
    
  end

  def extension_white_list
    %w(jpg jpeg png gif)
  end

  # def cache_dir    
  #   "#{Rails.root}/tmp/uploads"
  # end

  def store_dir
    "#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
  
  def filename
    # if model.name.present?
    #   "#{URI.escape(model.name.gsub(" ", "_"))}.jpg"
    # else
      original_filename.gsub(" ", "_") if original_filename.present?
    #end
  end

end

IN Site model
mount_uploader :logo, LogoUploader

and i am using Active admin
ActiveAdmin.register Site do
  
  #scope_to :current_admin_user, :if => proc{ admin_user_signed_in? && !current_admin_user.super_admin? }
  before_filter :only => [:create, :update] do
    logger.info "FFFFFFFFFFFFf #{params.inspect}"
    params[:site][:hotel_detail_attributes][:home_sub_menus] = params[:site][:hotel_detail_attributes][:home_sub_menus].reject(&:empty?).join(",")
    add_http_to_social    
  end

  before_filter :only => [:edit] do
    resource.hotel_detail.home_sub_menus = resource.hotel_detail.home_sub_menus.split(",") if !resource.hotel_detail.home_sub_menus.nil?
  end

end

**Comment by iamtarun** [comment]
Complete Error

```ruby
Unexpected exception in Dalli: NameError: uninitialized constant LogoUploader::Uploader87806260
This is a bug in Dalli, please enter an issue in Github if it does not already exist.
/home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:240:in `const_get'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:240:in `block in constantize'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:236:in `each'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:236:in `inject'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:236:in `constantize'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/core_ext/marshal.rb:10:in `rescue in load_with_autoloading'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/server.rb:424:in `deserialize'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/server.rb:488:in `generic_response'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/server.rb:257:in `get'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/server.rb:60:in `request'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/options.rb:18:in `block in request'
        /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/options.rb:17:in `request'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/client.rb:329:in `perform'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/client.rb:53:in `get'
        (eval):7:in `block in get_with_newrelic_trace'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.8.1.221/lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
        (eval):4:in `get_with_newrelic_trace'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:287:in `block in read_entry'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/dalli/client.rb:244:in `with'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:81:in `with'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:287:in `read_entry'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/cache/strategy/local_cache.rb:103:in `read_entry'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:91:in `block in fetch'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:350:in `block in instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:350:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.2/lib/active_support/cache/dalli_store.rb:90:in `fetch'
        /vagrant/commeasure/app/views/layouts/business_new.html.erb:162:in `_app_views_layouts_business_new_html_erb___3063495286526084647_71391760'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/template.rb:145:in `block in render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/template.rb:339:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/template.rb:143:in `render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:17:in `render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/rendering.rb:99:in `_render_template'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/rendering.rb:82:in `render_to_body'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/abstract_controller/rendering.rb:25:in `render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:16:in `render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
        /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:40:in `render'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/meta-tags-2.0.0/lib/meta_tags/controller_helper.rb:26:in `render_with_meta_tags'
        /vagrant/commeasure/app/controllers/home_controller.rb:9:in `index'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:189:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `run_callbacks'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:136:in `process'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionview-4.1.1/lib/action_view/rendering.rb:30:in `process'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal.rb:195:in `dispatch'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_controller/metal.rb:231:in `block in action'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:80:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:48:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:71:in `block in call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:59:in `each'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:59:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:676:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/oink-0.10.1/lib/oink/middleware.rb:17:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dragonfly-1.0.5/lib/dragonfly/middleware.rb:14:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/error_collector.rb:55:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/agent_hooks.rb:32:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/browser_monitoring.rb:27:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/developer_mode.rb:45:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rails4_client_side_validations-0.0.4/lib/rails4_client_side_validations/middleware.rb:21:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/flash.rb:254:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.1/lib/active_record/query_cache.rb:36:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/airbrake-3.1.17/lib/airbrake/rails/middleware.rb:13:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/rack/logger.rb:38:in `call_app'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `block in call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `tagged'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/actionpack-4.1.1/lib/action_dispatch/middleware/static.rb:64:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/heroku-deflater-0.5.3/lib/heroku-deflater/skip_binary.rb:19:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/heroku-deflater-0.5.3/lib/heroku-deflater/serve_zipped_assets.rb:50:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/dragonfly-1.0.5/lib/dragonfly/cookie_monster.rb:9:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/font_assets-0.1.11/lib/font_assets/middleware.rb:29:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/airbrake-3.1.17/lib/airbrake/user_informer.rb:16:in `_call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/airbrake-3.1.17/lib/airbrake/user_informer.rb:12:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/hirefire-resource-0.3.4/lib/hirefire/middleware.rb:29:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/engine.rb:514:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/application.rb:144:in `call'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `public_send'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `method_missing'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/passenger-4.0.58/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/passenger-4.0.58/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/passenger-4.0.58/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
        /home/vagrant/.rvm/gems/ruby-2.1.5/gems/passenger-4.0.58/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
127.0.0.1:11211 is down
#<Dalli::NetworkError: 127.0.0.1:11211 is down: NameError uninitialized constant LogoUploader::Uploader87806260>
retrying request with new server
down_retry_delay not reached for 127.0.0.1:11211 (1.000 seconds left)
DalliError: No server available

```

**Comment by petergoldstein** [comment]
So Carrierwave uploaders are not serializable by default, so you can't just take an uploader subclass and put it in Memcached via Dalli.  I believe there are some tools to support serialization of Carrierwave uploaders, but you'll have to investigate their availability.
