### ISSUE TITLE
socket.rb:85 rescue LoadError crashes ruby process

### ISSUE THREAD

**Issue by kosh-jelly** [mperham/dalli#539]
My sidekiq process is crashing in dalli/socket.rb:85

dalli version: 2.7.4
ruby version: 2.1.3
rails version: 4.1.2
sidekiq version: 3.3.5

This is happening after about 15 minutes of running, and after running plenty of different jobs that use the cache.

Here's the code that's calling the dalli cache:

````
	def self.keywords_sorted_by_spam_score
		Rails.cache.fetch("keywords_sorted_by_spam_score", expires_in: 12.hours) do
			all.order(spam_score: :desc).to_a
		end
	end
````

Here's the dump:
````
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/socket.rb:85: [BUG] Segmentation fault at 0x00000000000008
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0053 p:0035 s:0240 e:000239 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/socket.rb:85 [FINISH]
c:0052 p:---- s:0238 e:000237 CFUNC  :loop
c:0051 p:0015 s:0235 e:000234 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/socket.rb:83
c:0050 p:0020 s:0230 e:000229 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:551
c:0049 p:0045 s:0224 e:000223 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:484
c:0048 p:0069 s:0213 e:000212 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:261
c:0047 p:0059 s:0208 e:000207 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:63
c:0046 p:0012 s:0202 e:000201 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/options.rb:18
c:0045 p:0014 s:0200 e:000199 METHOD /home/deploy/.rbenv/versions/2.1.3/lib/ruby/2.1.0/monitor.rb:211
c:0044 p:0009 s:0197 e:000196 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/options.rb:17
c:0043 p:0074 s:0192 e:000191 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/client.rb:333
c:0042 p:0014 s:0181 e:000180 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/client.rb:56
c:0041 p:0017 s:0176 e:000174 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache/mem_cache_sto
c:0040 p:0070 s:0169 e:000168 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache/strategy/loca
c:0039 p:0012 s:0163 e:000162 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache/mem_cache_sto
c:0038 p:0026 s:0157 e:000156 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:560
c:0037 p:0089 s:0154 e:000153 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:548
c:0036 p:0013 s:0147 e:000146 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:558
c:0035 p:0051 s:0141 e:000140 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:290
c:0034 p:0025 s:0133 e:000132 METHOD /home/deploy/domain_freek/releases/317/app/models/spam_keyword.rb:57
c:0033 p:0014 s:0130 e:000129 METHOD /home/deploy/domain_freek/releases/317/app/models/spam_keyword.rb:41
c:0032 p:0016 s:0126 e:000125 METHOD /home/deploy/domain_freek/releases/317/app/models/domain_backlink.rb:63
c:0031 p:0056 s:0119 e:000118 METHOD /home/deploy/domain_freek/releases/317/app/models/domain_backlink.rb:51
c:0030 p:0035 s:0116 e:000115 METHOD /home/deploy/domain_freek/releases/317/app/workers/domain_backlink_fetcher.rb:8
c:0029 p:0010 s:0111 e:000110 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:75
c:0028 p:0020 s:0106 e:000105 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:52
c:0027 p:0014 s:0104 e:000103 LAMBDA /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.
c:0026 p:0008 s:0102 e:000101 METHOD /home/deploy/domain_freek/releases/317/config/initializers/sidekiq.rb:25
c:0025 p:0028 s:0096 e:000095 LAMBDA /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.
c:0024 p:0038 s:0094 e:000093 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8
c:0023 p:0028 s:0087 e:000086 LAMBDA /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.
c:0022 p:0006 s:0085 e:000084 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server
c:0021 p:0028 s:0081 e:000080 LAMBDA /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.
c:0020 p:0006 s:0079 e:000078 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server
c:0019 p:0028 s:0072 e:000071 LAMBDA /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.
c:0018 p:0029 s:0070 E:000260 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server
c:0017 p:0056 s:0067 e:000066 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/logging.rb:24
c:0016 p:0072 s:0063 E:001f58 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server
c:0015 p:0028 s:0056 e:000055 LAMBDA /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain. [FINISH]
c:0014 p:---- s:0054 e:000053 CFUNC  :call
c:0013 p:0024 s:0051 E:002290 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.
c:0012 p:0021 s:0045 E:001618 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:51
c:0011 p:0016 s:0043 E:0015d0 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:98
c:0010 p:0107 s:0037 E:001628 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:50 [FINISH]
c:0009 p:---- s:0026 e:000025 CFUNC  :public_send
c:0008 p:0040 s:0021 e:000020 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26
c:0007 p:0031 s:0016 e:000015 METHOD /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122
c:0006 p:0011 s:0011 e:000010 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60
c:0005 p:0041 s:0009 e:000008 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71
c:0004 p:0026 s:0007 e:000006 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357
c:0003 p:0073 s:0005 e:000004 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57
c:0002 p:0060 s:0003 e:000002 BLOCK  /home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15 [FINISH]
c:0001 p:---- s:0001 e:000000 ------

-- Ruby level backtrace information ----------------------------------------
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:50:in `process'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:98:in `stats'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:51:in `block in process'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server/logging.rb:11:in `call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/logging.rb:24:in `with_context'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8:in `call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/domain_freek/releases/317/config/initializers/sidekiq.rb:25:in `call'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/bundler/gems/sidekiq-54caccd04f8d/lib/sidekiq/processor.rb:75:in `execute_job'
/home/deploy/domain_freek/releases/317/app/workers/domain_backlink_fetcher.rb:8:in `perform'
/home/deploy/domain_freek/releases/317/app/models/domain_backlink.rb:51:in `perform_fetch'
/home/deploy/domain_freek/releases/317/app/models/domain_backlink.rb:63:in `process_anchors_for_spam'
/home/deploy/domain_freek/releases/317/app/models/spam_keyword.rb:41:in `top_match_for'
/home/deploy/domain_freek/releases/317/app/models/spam_keyword.rb:57:in `keywords_sorted_by_spam_score'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:290:in `fetch'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:558:in `find_cached_entry'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:548:in `instrument'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache.rb:560:in `block in find_cached_entry'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache/mem_cache_store.rb:179:in `read_entry'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache/strategy/local_cache.rb:109:in `read_entry'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/cache/mem_cache_store.rb:124:in `read_entry'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/client.rb:56:in `get'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/client.rb:333:in `perform'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/options.rb:17:in `request'
/home/deploy/.rbenv/versions/2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/options.rb:18:in `block in request'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:63:in `request'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:261:in `get'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:484:in `generic_response'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/server.rb:551:in `read'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/socket.rb:83:in `readfull'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/socket.rb:83:in `loop'
/home/deploy/domain_freek/releases/317/vendor/bundle/ruby/2.1.0/gems/dalli-2.7.4/lib/dalli/socket.rb:85:in `block in readfull'

-- C level backtrace information -------------------------------------------
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x188efc) [0x7f8561264efc]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x1fb823) [0x7f85612d7823]
sidekiq 3.3.5 domain_freek [10 of 10 busy](rb_bug+0xb3) [0x7f85612d8a03]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0xfdf8f) [0x7f85611d9f8f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f8560ca9340] ../nptl/sysdeps/pthread/funlockfile.c:29
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x3f049) [0x7f856111b049]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x3f8d8) [0x7f856111b8d8]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x4208a) [0x7f856111e08a]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x403ad) [0x7f856111c3ad]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x417c8) [0x7f856111d7c8]
sidekiq 3.3.5 domain_freek [10 of 10 busy](ruby_xmalloc+0x50) [0x7f8561121f10]
/home/deploy/.rbenv/versions/2.1.3/lib/ruby/2.1.0/x86_64-linux/objspace.so(+0x2f56) [0x7f8518172f56] object_tracing.c:98
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x18c9d9) [0x7f85612689d9]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x18f8ff) [0x7f856126b8ff]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x20bde) [0x7f85610fcbde]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x4271a) [0x7f856111e71a]
sidekiq 3.3.5 domain_freek [10 of 10 busy](rb_node_newnode+0x27) [0x7f856111e7d7]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x178972) [0x7f8561254972]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17addf) [0x7f8561256ddf]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17e2ea) [0x7f856125a2ea]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17ef54) [0x7f856125af54]
sidekiq 3.3.5 domain_freek [10 of 10 busy](rb_rescue2+0xbe) [0x7f8561102b0e]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x170e3e) [0x7f856124ce3e]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x172574) [0x7f856124e574]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x177ad5) [0x7f8561253ad5]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17addf) [0x7f8561256ddf]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17e2ea) [0x7f856125a2ea]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17eacb) [0x7f856125aacb]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17eb7a) [0x7f856125ab7a]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x2a140) [0x7f8561106140]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x172574) [0x7f856124e574]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x177194) [0x7f8561253194]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17addf) [0x7f8561256ddf]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17c514) [0x7f8561258514]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17d27b) [0x7f856125927b]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x1814fe) [0x7f856125d4fe]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x180bb1) [0x7f856125cbb1]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x177ad5) [0x7f8561253ad5]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17addf) [0x7f8561256ddf]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17e2ea) [0x7f856125a2ea]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17eacb) [0x7f856125aacb]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x17eb7a) [0x7f856125ab7a]
sidekiq 3.3.5 domain_freek [10 of 10 busy](+0x1a0278) [0x7f856127c278]
/lib/x86_64-linux-gnu/libc.so.6(+0x498b0) [0x7f85601da8b0] grouping.c:201

-- Other runtime information -----------------------------------------------

* Loaded script: sidekiq 3.3.5 domain_freek [10 of 10 busy]

[abbridged]

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
````

**Comment by mperham** [comment]
Update your Ruby VM and all native gems to the latest versions.

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do

**Comment by kosh-jelly** [comment]
Thank you so much. Working just fine now. 

I feel a bit foolish for not doing that before submitting the issue. My bad.
