### ISSUE TITLE
Unexpected exception during Dalli request: ArgumentError: comparison of ActiveSupport::TimeWithZone with 2592000 failed

### ISSUE THREAD

**Issue by masterkain** [mperham/dalli#543]
I have a rails app configured as:

```
config.cache_store = :dalli_store, ENV['MEMCACHED_HOST'], { pool: 5, expires_in: 1296000, compress: true, socket_timeout: 1.5, socket_failure_delay: 0.2 }
```

I have the connection pool gem, I'm getting this exception during startup:

```
Unexpected exception during Dalli request: ArgumentError: comparison of ActiveSupport::TimeWithZone with 2592000 failed
myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/server.rb:474:in `>'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/server.rb:474:in `sanitize_ttl'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/server.rb:275:in `set'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/server.rb:63:in `request'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/options.rb:18:in `block in request'
  /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/options.rb:17:in `request'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/client.rb:333:in `perform'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/client.rb:107:in `set'
  myapp/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/memcache.rb:48:in `block (4 levels) in instrument_methods'
  myapp/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  myapp/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  myapp/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  myapp/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/memcache.rb:45:in `block (3 levels) in instrument_methods'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:303:in `write_entry'
  myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:133:in `block (2 levels) in write'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/dalli/client.rb:248:in `with'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:81:in `with'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:131:in `block in write'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:359:in `block in instrument'
  myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:161:in `instrument'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:359:in `instrument'
  myapp/shared/bundle/ruby/2.2.0/gems/dalli-2.7.4/lib/active_support/cache/dalli_store.rb:130:in `write'
  myapp/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/caching/fragments.rb:33:in `block in write_fragment'
  myapp/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/caching/fragments.rb:93:in `block in instrument_fragment_cache'
  myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `block in instrument'
  myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `instrument'
  myapp/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/caching/fragments.rb:93:in `instrument_fragment_cache'
  myapp/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/caching/fragments.rb:31:in `write_fragment'
  myapp/shared/bundle/ruby/2.2.0/gems/actionview-4.1.11/lib/action_view/helpers/cache_helper.rb:196:in `write_fragment_for'
  myapp/shared/bundle/ruby/2.2.0/gems/actionview-4.1.11/lib/action_view/helpers/cache_helper.rb:179:in `fragment_for'
  myapp/shared/bundle/ruby/2.2.0/gems/actionview-4.1.11/lib/action_view/helpers/cache_helper.rb:115:in `cache'
```

**Comment by masterkain** [comment]
this is probably due to a .from_now leftover in code. sorry for the noise.
