### ISSUE TITLE
Unexpected exception in Dalli: NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by pikender** [mperham/dalli#544]
When *upgrading to Rails 4.1.9 from Rails 3.2.16*, below error occured and site crashed.

Please refer the backtrace of error / exception

*Dalli version: 2.6.2*
*Ruby Version: 2.0.0-p451*

```ruby
Unexpected exception in Dalli: NoMethodError: undefined method `[]' for nil:NilClass
This is a bug in Dalli, please enter an issue in Github if it does not already exist.

/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/attribute_methods/read.rb:113:in `block in read_attribute'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/attribute_methods/read.rb:111:in `fetch'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/attribute_methods/read.rb:111:in `read_attribute'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/attribute_methods/primary_key.rb:20:in `id'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/core.rb:310:in `hash'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/core_ext/marshal.rb:6:in `load'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/server.rb:420:in `deserialize'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/server.rb:471:in `generic_response'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/server.rb:251:in `get'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/server.rb:55:in `request'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/options.rb:18:in `block in request'
	/usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/options.rb:17:in `request'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/client.rb:321:in `perform'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/dalli/client.rb:52:in `get'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/memcache.rb:48:in `block (4 levels) in instrument_methods'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/memcache.rb:45:in `block (3 levels) in instrument_methods'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/active_support/cache/dalli_store.rb:222:in `read_entry'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/cache/strategy/local_cache.rb:104:in `read_entry'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/active_support/cache/dalli_store.rb:67:in `block in fetch'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/active_support/cache/dalli_store.rb:279:in `block in instrument'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:161:in `instrument'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/active_support/cache/dalli_store.rb:279:in `instrument'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/dalli-2.6.2/lib/active_support/cache/dalli_store.rb:65:in `fetch'
	/home/vinsol/apps/dd_rails4_staging/releases/20150722134112/app/controllers/application_controller.rb:494:in `data_cache'
	/home/vinsol/apps/dd_rails4_staging/releases/20150722134112/lib/deal_listing_methods.rb:3:in `load_category_items'
	/home/vinsol/apps/dd_rails4_staging/releases/20150722134112/app/controllers/home_controller.rb:27:in `load_deals_for_web'
	/home/vinsol/apps/dd_rails4_staging/releases/20150722134112/app/controllers/home_controller.rb:13:in `block (2 levels) in index'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/mime_responds.rb:258:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/mime_responds.rb:258:in `respond_to'
	/home/vinsol/apps/dd_rails4_staging/releases/20150722134112/app/controllers/home_controller.rb:11:in `index'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/abstract_controller/base.rb:189:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/rendering.rb:10:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:229:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:299:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:299:in `block (2 levels) in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:447:in `public_send'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:447:in `block in make_lambda'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:298:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:298:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/abstract_controller/callbacks.rb:19:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/rescue.rb:29:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:159:in `block in instrument'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:159:in `instrument'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/abstract_controller/base.rb:136:in `process'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionview-4.1.9/lib/action_view/rendering.rb:30:in `process'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal.rb:196:in `dispatch'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_controller/metal.rb:232:in `block in action'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:82:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:50:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/journey/router.rb:73:in `block in call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/journey/router.rb:59:in `each'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/journey/router.rb:59:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:685:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-mobile-detect-0.4.0/lib/rack/mobile-detect.rb:164:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/releases/20150722134112/lib/utf8_sanitizer.rb:22:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/flash.rb:254:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/cookies.rb:562:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/query_cache.rb:36:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/airbrake-4.0.0/lib/airbrake/rails/middleware.rb:13:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:38:in `call_app'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:22:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/static.rb:84:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/airbrake-4.0.0/lib/airbrake/user_informer.rb:16:in `_call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/airbrake-4.0.0/lib/airbrake/user_informer.rb:12:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/engine.rb:514:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application.rb:144:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:552:in `process_client'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:632:in `worker_loop'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:142:in `start'
	/home/vinsol/apps/dd_rails4_staging/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/bin/unicorn_rails:209:in `<top (required)>'
	/usr/local/bin/unicorn_rails:23:in `load'
	/usr/local/bin/unicorn_rails:23:in `<main>'
```

**Comment by petergoldstein** [comment]
@pikender Despite the text of the error message, this is unlikely to be an error in Dalli.  My suspicion is that this is a serialization error resulting from the deserialization with Rails 4.x of an object that was originally serialized with Rails 3.x

Is that a possibility?  When you upgraded from Rails 3.x to Rails 4.x did you make sure to clear memcached (ideally by stopping and restarting it)?

**Comment by pikender** [comment]
@petergoldstein, no we didn't restarted memcache but *restarting does solves the problem* :)

**Comment by petergoldstein** [comment]
@pikender Ok, that's almost certainly the issue then.  Closing.  Please reopen or file another issue if the problem reappears.
